events {
    worker_connections 1024;
}

http {
    upstream rss-reader {
        server rss-reader-app:3000;
    }

    # HTTP Server - For initial SSL setup
    server {
        listen 80;
        server_name streamlet.taranezy.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Temporarily allow all traffic for SSL setup
        location / {
            proxy_pass http://rss-reader;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
